### ISSUE TITLE
Custom menus crash in tablet mode

### ISSUE THREAD

**Issue by sooti** [scotthartbti/android_packages_apps_Settings#8] opened 2014-02-04 22:50 UTC
Hey scott,  I built your rom for the nexus 10, all the menus in the settings menu except the custom ones you put in there work, yours crash the settingsUI

its an issue I noticed with other roms with no official tablet support, wondering if you could just fix this issue, once I see the code used I can also fix it for other roms :)

hint: obviously cm 11 by default can tell the difference between phone UI and tablet UI, but with your menus they can't so they crash, must be something in the CM menus that will help

**Comment by scotthartbti** [comment] 2014-02-05 15:31
Well since I'm not running this on a tablet I'll never be able to reproduce
the issue... If you want something fixed a logcat of the fc would be a good
thing to include so I have an idea of what your seeing or what the issue is.

**Comment by Cl3Kener** [comment] 2014-02-05 15:38
Scott,  you can actually force dual pane preferences which is thanks once again to another Scott (Scott Brady)

See here:
https://github.com/sgt7/android_frameworks_base/commit/c834f64b3d22d5616798ca4d26c4991f6da744b0

https://github.com/sgt7/android_packages_apps_Settings/commit/7336e79e6b1784cfa76922ca15e018f833e3be14

Unfortunately he didn't separate commits but I'm sure you'll figure it out :)

This is how you can reproduce tablet errors on any device. Personally I like dual pane when in landscape on my phone.  Might be worth the extra feature of having all the time or only in landscape as SBrady has it.

**Comment by Cl3Kener** [comment] 2014-02-05 15:44
Even if it's a pita to fix all of your menus I think this feature should allow for sooti to just use normal menus which will keep them from crashing on him.  You'll have to make sure to put it in an aosp submenu to make sure he can access it though.

**Comment by sooti** [comment] 2014-02-05 15:48
Yup CIKener, that's the issue, the dual menu's, scott it would be amazing if you could do it :)

Basicly there's no support for dual panel in your menus, thats what it comes down to

I think slimrom forces phone mode for menu's in their rom

I'll upload the logcat when I get home since my tablet isn't with me

Missing fragment, that was the error

**Comment by sooti** [comment] 2014-02-05 16:00
Found it :)

http://www.vogella.com/tutorials/AndroidFragments/article.html

add 

'package com.android.settings.cyanogenmod.fragments;'

and

 'import com.android.settings.SettingsPreferenceFragment;'

in the begining

then when the menu starts:

'public class settingname extends SettingsPreferenceFragment {'

**Comment by Cl3Kener** [comment] 2014-02-05 16:05
sooti, let me tweak your above comment just a bit (trying to help you out here with your wording so Scott will want to help us out here).  It's never a question about if Scott "could do it."  (Of course Scott could do it! This is Scott we're talking about here!!!)  It's more of a question of if it's worth it to him to do it or when he'll do it.  I think what you really meant is "Scott, Cl3Kener is right about dual panel being the issue, it would be amazing if you will take a few precious minutes of your time (since we know you are busy) and add this dual panel option for people who own tablets (like both of us).  There are enough people besides just the two of us that are tablet owning HARDCORE Beanstalk Fans that I think it will be well worth your time.  Thanks for all of your hard work on Beanstalk! This is an EXCELLENT ROM and we'd love to have it work on our Tablets as well as our phones!!! :+1: "

**Comment by sooti** [comment] 2014-02-05 16:08
Yes scott! thank you!! I want to bring your amazing rom to the folks using nexus 10s so that they can enjoy it too :D

Didn't mean to sound like a brat lol

**Comment by scotthartbti** [comment] 2014-02-05 17:45
Thanks for the responses and research, but you still haven't provided a
logcat of the crash... Please do so.  Also, it may help to communicate
directly with you for testing purposes.  Do you use hangouts?

**Comment by sooti** [comment] 2014-02-05 17:53
yes sooti85@gmail.com

just got home ill get the logcat

**Comment by sooti** [comment] 2014-02-05 18:11
heres the logcat

http://pastebin.com/wE4Jhn30

I used two menus that crash, beanstalk options and about beanstalk

starts at line 2506

**Comment by scotthartbti** [comment] 2014-02-05 18:49
Thanks.  I'll shoot you a hangout invitation in a bit.

**Comment by scotthartbti** [comment] 2014-02-05 19:08
Just curious... Does the lock screen menu open ok for you?

**Comment by scotthartbti** [comment] 2014-02-05 20:54
I have the fix for this.  I will implement it one of two ways later this evening.  Depending on time i will either edit my custom layouts i have added to follow the standards that CM has done a ways back or i will revert the CM commit to force single screen tablet layouts.  Either way.. this is as good as resolved.  Will post link to the commit before closing.

**Comment by scotthartbti** [comment] 2014-02-06 05:31
This should be fixed with this commit d4329ec55181db54cfb683be808589c6c092614f - Tablets should open with single pane now.  Let me know if you continue to see a problem.

**Closed as completed by scotthartbti** 2014-02-06 05:31 UTC
